kafka: 
  name: my-cluster

strimzi-kafka-operator:
  dashboards:
    enabled: true
    namespace: monitoring
  featureGates: +UseKRaft,+KafkaNodePools,+UnidirectionalTopicOperator
  strimzi-kafka-operator:
    watchAnyNamespace: true
  kafka:
    limits:
      memory: 1G
      cpu: 300m
    requests:
      memory: 384Mi
      cpu: 200m